bot:

  url: wss://test.deribit.com/ws/api/v2

  order_label: 'dsb'
  
  logger: 'derebit_bot'
  
  auth:
    grant_type: 'client_credentials'
    client_id: ''
    client_secret: ''
    
  instrument:
    default:
      gap: 100.0
      gap_ignore: 50.0
      price_id: 'mark_price'
      amount: 10
    btc-perpetual:
    eth-perpetual:


synch:
  mod: 1
  actual: True


db: &db-cred
  user: 'root'
  password: ''
  host: '127.0.0.1'
  database: 'deribit_test_bot'
  charset: 'utf8mb4'


logging:
  version: 1
  
  formatters:
    simple:
      format: '%(asctime)s %(name)s [%(levelname)s]: %(message)s'

  handlers:
    console:
      class: 'logging.StreamHandler'
      level: 'INFO'
      formatter: 'simple'
      stream: 'ext://sys.stdout'
    file:
      class: 'logging.FileHandler'
      level: 'WARNING'
      filename: 'bot_log.log'
    mysqldb:
      class: 'deribitsimplebot.db.CLogMySQLHandler'
      level: 'INFO'
      <<: *db-cred

  loggers:
    derebit_bot:
      handlers: [mysqldb, file]

  root:
    level: 'INFO'
    handlers: [console,file]